name: testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libpango1.0-dev libfontconfig1-dev

      - name: Run unit tests
        run: cargo test

  pack-check-render:
    name: Tutorial Pack Check Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev libcairo2-dev libpango1.0-dev libfontconfig1-dev

      - name: Run tutorial commands
        run: |
          mkdir -p ./out
          cargo run -- pack ./docs/tutorial/tutorial.psl tutorial -f test/fonts/Kablammo.ttf -o ./out -s ./docs/tutorial/FRAME_QR_CODES.lua -s ./docs/tutorial/FRAME_LOGO.lua -a test/images/save-5.png --remap ./docs/tutorial/remap.plt
          cargo run -- check ./out/tutorial.marmot ./docs/tutorial/tutorial.json
          cargo run -- render ./out/tutorial.marmot ./docs/tutorial/tutorial.json --output ./out/tutorial.pdf
          cargo run -- render ./out/tutorial.marmot ./docs/tutorial/tutorial.json --output ./out/tutorial.png --output-type png --dither atkinson
